[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django_resaas"
version = "0.0.486"
description = "Django SAAS Framework"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

authors = [
  { name = "Dias Metano Salvador Chavana", email = "metanochava@gmail.com" }
]

keywords = ["django", "saas", "framework"]

classifiers = [
  "Framework :: Django",
  "Programming Language :: Python :: 3",
]

dependencies = [
  "Django==5.2.10",
  "djangorestframework==3.16.1",
  "djangorestframework_simplejwt==5.5.1",
  "Pillow",
  "pyotp",
  "qrcode[pil]>=7.4.2",
  "python-barcode==0.15.1",
  "black",
  "gunicorn",
  "weasyprint",
  "django-money",
  "python-dotenv",
  "django-cors-headers",
  "psycopg[binary]",
  "django-filter",
  "dotenv==0.9.9",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "pytest-django>=4.8",
  "factory_boy>=3.3",
  "celery>=5.3",
]
notifications = [
  "celery>=5.3",
]

[project.urls]
Homepage = "https://github.com/metanochava/django_resaas"
Repository = "https://github.com/metanochava/django_resaas"

# 🔥 CONFIGURAÇÃO CRÍTICA
[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true   # ✅ ESSENCIAL (FALTAVA)

[tool.setuptools.packages.find]
where = ["src"]
include = ["django_resaas*"]

# 🔥 GARANTE QUE TEMPLATES ENTRAM NO BUILD
[tool.setuptools.package-data]
"django_resaas.engine" = [
  "templates/**/*"
]
"django_resaas.hr" = [
  "templates/**/*"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "dev.settings"
pythonpath = ["src"]
addopts = "-q"
testpaths = ["src"]