# hr/views/payslip.py

from rest_framework.response import Response
from rest_framework import status

from django_resaas.engine.core.base.views import BaseAPIView, registerView

from django_resaas.hr.models.payslip import Payslip
from django_resaas.hr.serializers.payslip import PayslipSerializer


@registerView('payslips', module='hr')
class PayslipAPIView(BaseAPIView):
    queryset = Payslip.objects.all()
    serializer_class = PayslipSerializer

    # A Payslip is a snapshot only produced by
    # PayrollAPIView.confirm() (hr/services/payroll_service.py -
    # confirm_payroll) - a free POST here would create an empty payslip
    # detached from any real Payroll totals, same reasoning as
    # EmployeeOnboarding (Fase 5) / EmployeeTraining (Fase 7).
    def create(self, request, *args, **kwargs):
        return Response(
            {"detail": "Payslips are generated by POST /hr/payrolls/{id}/confirm/."},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    # .pdf() (GET .../payslips/{id}/pdf/) is inherited for free from
    # BaseAPIView - see get_pdf_template()/get_pdf_context()/pdf() in
    # engine/core/base/views.py. It resolves hr/payslip.html before
    # falling back to django_resaas/pdf/detail.html (see
    # hr/templates/hr/payslip.html).
