# Generated by Django 5.2.10 on 2026-05-18 19:23

import django.db.models.deletion
import django_resaas.core.base.mixins.model.label_value
import django_resaas.models.document
import django_resaas.models.entity
import django_resaas.models.entity_type
import django_resaas.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fek", models.CharField(max_length=255, unique=True)),
                ("fep", models.CharField(max_length=255)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("readwrite", "Read & Write"),
                            ("super", "Super"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Ativo")], default=1
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        default="user.png",
                        null=True,
                        upload_to=django_resaas.models.user.profile_image_path,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default=None, max_length=55, null=True, unique=True
                    ),
                ),
                ("is_verified_mobile", models.BooleanField(default=False)),
                ("counter", models.IntegerField(default=0)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_verified_email", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("rua", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(default="Moçambique", max_length=100)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("complemento", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="AnimationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enable_animations", models.BooleanField(default=True)),
                (
                    "animation_speed",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("normal", "Normal"),
                            ("fast", "Fast"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "page_transition",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fade", "Fade"),
                            ("slide-left", "Slide Left"),
                            ("slide-right", "Slide Right"),
                            ("slide-up", "Slide Up"),
                            ("slide-down", "Slide Down"),
                            ("scale", "Scale"),
                            ("zoom", "Zoom"),
                        ],
                        default="fade",
                        max_length=50,
                    ),
                ),
                (
                    "button_animation",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("ripple", "Ripple"),
                            ("pulse", "Pulse"),
                            ("bounce", "Bounce"),
                            ("scale", "Scale"),
                        ],
                        default="ripple",
                        max_length=50,
                    ),
                ),
                ("hover_effect", models.BooleanField(default=True)),
                (
                    "hover_style",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("lift", "Lift"),
                            ("shadow", "Shadow"),
                            ("grow", "Grow"),
                            ("glow", "Glow"),
                        ],
                        default="lift",
                        max_length=50,
                    ),
                ),
                (
                    "card_animation",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fade", "Fade"),
                            ("slide-up", "Slide Up"),
                            ("zoom", "Zoom"),
                        ],
                        default="fade",
                        max_length=50,
                    ),
                ),
                (
                    "modal_animation",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("scale", "Scale"),
                            ("fade", "Fade"),
                            ("slide-up", "Slide Up"),
                        ],
                        default="scale",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Setting",
                "verbose_name_plural": "Animation Settings",
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CorsAllowedOrigin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("origin", models.URLField(unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("detalhes", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(default="-", max_length=100, null=True)),
                ("site", models.CharField(default="-", max_length=300, null=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="logo.png",
                        upload_to=django_resaas.models.entity.logo_path,
                    ),
                ),
                (
                    "display_logo",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "display_bar",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "display_qr",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("rodape", models.CharField(max_length=2000, null=True)),
                ("disc_space", models.FloatField(default=1048576.0, null=True)),
                ("disc_used_space", models.FloatField(default=0.0, null=True)),
                ("disc_free_space", models.FloatField(default=1048576.0, null=True)),
                ("admins", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "animation_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_resaas.animationsetting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("rodape", models.CharField(default=".", max_length=600, null=True)),
                ("icon", models.CharField(default=".", max_length=100, null=True)),
                ("label", models.CharField(default=".", max_length=100, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_resaas.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entity",
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        default="logo.png",
                        upload_to=django_resaas.models.entity_type.icon_path,
                    ),
                ),
                ("license", models.TextField(default="license")),
                ("label", models.CharField(max_length=100, null=True)),
                ("ordem", models.IntegerField(default=2)),
                ("crair_entity", models.BooleanField(default=True, null=True)),
                (
                    "animation_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_resaas.animationsetting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="entity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_resaas.entitytype",
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="files")),
                ("size", models.FloatField()),
                (
                    "model",
                    models.CharField(
                        help_text="Name do model que originou o file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactivo"), (1, "Active")], default=1, null=True
                    ),
                ),
                (
                    "funcionalidade",
                    models.CharField(
                        choices=[
                            ("File", "File"),
                            ("Profile", "Profile"),
                            ("Logo", "Logo"),
                            ("Photo", "Photo"),
                            ("Cover", "Cover"),
                        ],
                        default="File",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("chamador", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("editable", models.BooleanField(default=False)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="resaas_groups", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.language",
            ),
        ),
        migrations.CreateModel(
            name="LayoutSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                ("buttonDense", models.BooleanField(default=False)),
                ("buttonRounded", models.BooleanField(default=False)),
                ("buttonSquare", models.BooleanField(default=False)),
                ("inputDense", models.BooleanField(default=False)),
                ("inputRounded", models.BooleanField(default=False)),
                ("inputSquare", models.BooleanField(default=False)),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("dense", "Dense"),
                            ("normal", "Normal"),
                            ("comfortable", "Comfortable"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("animations", models.BooleanField(default=True)),
                ("button_dense", models.BooleanField(default=False)),
                ("button_round", models.BooleanField(default=False)),
                (
                    "input_style",
                    models.CharField(
                        choices=[
                            ("outlined", "Outlined"),
                            ("filled", "Filled"),
                            ("standout", "Standout"),
                        ],
                        default="outlined",
                        max_length=20,
                    ),
                ),
                ("input_dense", models.BooleanField(default=False)),
                ("border_radius", models.IntegerField(default=8)),
                ("sidebar_width", models.IntegerField(default=260)),
                ("toolbar_dense", models.BooleanField(default=False)),
                ("toolbar_elevated", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=101)),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("outline", "Outline"),
                            ("unelevated", "Unelevated"),
                            ("push", "Push"),
                        ],
                        default="unelevated",
                        max_length=20,
                    ),
                ),
                ("dense", models.BooleanField(default=False)),
                ("rounded", models.BooleanField(default=False)),
                ("square", models.BooleanField(default=False)),
                ("ripple", models.BooleanField(default=True)),
                ("elevated", models.BooleanField(default=True)),
                ("card_flat", models.BooleanField(default=False)),
                ("card_bordered", models.BooleanField(default=False)),
                ("sidebar_mini", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LayoutSetting",
                "verbose_name_plural": "LayoutSettings",
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="layout_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.layoutsetting",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="layout_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.layoutsetting",
            ),
        ),
        migrations.CreateModel(
            name="ModelExtra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("model", models.CharField(max_length=100, null=True)),
                ("icon", models.CharField(max_length=100, null=True)),
                ("method", models.CharField(max_length=50, null=True)),
                ("permission", models.CharField(max_length=100, null=True)),
                ("details", models.BooleanField(default=False)),
                ("url", models.CharField(max_length=300, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary", models.CharField(default="#1976D2", max_length=50)),
                ("secondary", models.CharField(default="#26A69A", max_length=50)),
                ("accent", models.CharField(default="#9C27B0", max_length=50)),
                ("positive", models.CharField(default="#21BA45", max_length=50)),
                ("negative", models.CharField(default="#C10015", max_length=50)),
                ("warning", models.CharField(default="#F2C037", max_length=50)),
                ("info", models.CharField(default="#31CCEC", max_length=50)),
                ("dark", models.CharField(default="#1D1D1D", max_length=50)),
                ("light", models.CharField(default="#FFFFFF", max_length=50)),
                ("background", models.CharField(default="#F6F8F7", max_length=50)),
                ("background_dark", models.CharField(default="#121212", max_length=50)),
                ("page", models.CharField(default="#FFFFFF", max_length=50)),
                ("card", models.CharField(default="#FFFFFF", max_length=50)),
                ("text_primary", models.CharField(default="#000000", max_length=50)),
                ("text_secondary", models.CharField(default="#666666", max_length=50)),
                ("text_muted", models.CharField(default="#9E9E9E", max_length=50)),
                ("text_light", models.CharField(default="#FFFFFF", max_length=50)),
                ("text_dark", models.CharField(default="#1D1D1D", max_length=50)),
                ("text_link", models.CharField(default="#1976D2", max_length=50)),
                ("header", models.CharField(default="#1976D2", max_length=50)),
                ("header_text", models.CharField(default="#FFFFFF", max_length=50)),
                ("footer", models.CharField(default="#1976D2", max_length=50)),
                ("footer_text", models.CharField(default="#FFFFFF", max_length=50)),
                ("sidebar", models.CharField(default="#FFFFFF", max_length=50)),
                ("sidebar_text", models.CharField(default="#333333", max_length=50)),
                ("sidebar_active", models.CharField(default="#1976D2", max_length=50)),
                (
                    "sidebar_active_text",
                    models.CharField(default="#FFFFFF", max_length=50),
                ),
                ("sidebar_hover", models.CharField(default="#F5F5F5", max_length=50)),
                ("button_primary", models.CharField(default="#1976D2", max_length=50)),
                (
                    "button_primary_text",
                    models.CharField(default="#FFFFFF", max_length=50),
                ),
                (
                    "button_secondary",
                    models.CharField(default="#26A69A", max_length=50),
                ),
                (
                    "button_secondary_text",
                    models.CharField(default="#FFFFFF", max_length=50),
                ),
                ("button_outline", models.CharField(default="#1976D2", max_length=50)),
                (
                    "input_background",
                    models.CharField(default="#FFFFFF", max_length=50),
                ),
                ("input_border", models.CharField(default="#CCCCCC", max_length=50)),
                ("input_focus", models.CharField(default="#1976D2", max_length=50)),
                ("border", models.CharField(default="#E0E0E0", max_length=50)),
                ("divider", models.CharField(default="#EEEEEE", max_length=50)),
                ("grey", models.CharField(default="#CDCDCD", max_length=50)),
                ("grey_1", models.CharField(default="#FAFAFA", max_length=50)),
                ("grey_2", models.CharField(default="#F5F5F5", max_length=50)),
                ("grey_3", models.CharField(default="#EEEEEE", max_length=50)),
                ("grey_4", models.CharField(default="#E0E0E0", max_length=50)),
                ("grey_5", models.CharField(default="#BDBDBD", max_length=50)),
                ("grey_6", models.CharField(default="#9E9E9E", max_length=50)),
                ("grey_7", models.CharField(default="#757575", max_length=50)),
                ("grey_8", models.CharField(default="#616161", max_length=50)),
                ("grey_9", models.CharField(default="#424242", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.theme",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.theme",
            ),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("chave", models.TextField(blank=True, null=True)),
                ("translation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Typography",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("Roboto", "Roboto"),
                            ("Inter", "Inter"),
                            ("Open Sans", "Open Sans"),
                            ("Lato", "Lato"),
                            ("Poppins", "Poppins"),
                            ("Montserrat", "Montserrat"),
                            ("Source Sans Pro", "Source Sans Pro"),
                            ("Nunito", "Nunito"),
                            ("Raleway", "Raleway"),
                            ("Ubuntu", "Ubuntu"),
                            ("Playfair Display", "Playfair Display"),
                            ("Merriweather", "Merriweather"),
                        ],
                        default="Roboto",
                        max_length=100,
                    ),
                ),
                (
                    "font_family_monospace",
                    models.CharField(
                        choices=[
                            ("monospace", "Default Monospace"),
                            ("Fira Code", "Fira Code"),
                            ("JetBrains Mono", "JetBrains Mono"),
                            ("Source Code Pro", "Source Code Pro"),
                            ("Roboto Mono", "Roboto Mono"),
                        ],
                        default="monospace",
                        max_length=100,
                    ),
                ),
                ("font_size_base", models.IntegerField(default=14)),
                ("font_size_h1", models.IntegerField(default=32)),
                ("font_size_h2", models.IntegerField(default=28)),
                ("font_size_h3", models.IntegerField(default=24)),
                ("font_size_h4", models.IntegerField(default=20)),
                ("font_size_h5", models.IntegerField(default=18)),
                ("font_size_h6", models.IntegerField(default=16)),
                ("font_size_body", models.IntegerField(default=14)),
                ("font_size_caption", models.IntegerField(default=12)),
                ("font_size_small", models.IntegerField(default=11)),
                ("font_weight_light", models.IntegerField(default=300)),
                ("font_weight_normal", models.IntegerField(default=400)),
                ("font_weight_medium", models.IntegerField(default=500)),
                ("font_weight_bold", models.IntegerField(default=700)),
                ("line_height", models.FloatField(default=1.5)),
                ("letter_spacing", models.FloatField(default=0)),
                ("uppercase_headings", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Typography",
                "verbose_name_plural": "Typography",
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="typography",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.typography",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="typography",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.typography",
            ),
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("dispositivo", models.TextField(null=True)),
                ("mobile", models.CharField(max_length=100, null=True)),
                ("info", models.TextField(null=True)),
                ("local_lat", models.CharField(max_length=100, null=True)),
                ("local_lon", models.CharField(max_length=100, null=True)),
                ("local_name", models.CharField(max_length=100, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BranchUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("branch", "user")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("numero", models.CharField(max_length=100)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=django_resaas.models.document.document_path,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.documenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("tipo", "numero")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.app",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity", "app")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity", "model")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityTypeApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.app",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entitytype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity_type", "app")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityTypeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entitytype",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity_type", "model")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity", "user")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityTypeGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_type_groups",
                        to="django_resaas.entitytype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_entity_types",
                        to="django_resaas.group",
                    ),
                ),
            ],
            options={
                "unique_together": {("entity_type", "group")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EntityGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.group",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("entity", "group")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BranchUserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.group",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("branch", "user", "group")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BranchGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_resaas.group",
                    ),
                ),
            ],
            options={
                "permissions": (),
                "unique_together": {("branch", "group")},
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("surname", models.CharField(max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "telefone_alternativo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="django_resaas.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="django_resa_name_1d1fb3_idx"),
                    models.Index(fields=["email"], name="django_resa_email_9b9ce4_idx"),
                ],
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
