# Generated by Django 5.2.10 on 2026-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculine"), ("F", "Feminine"), ("O", "Others")],
                null=True,
            ),
        ),
    ]
