# Generated by Django 5.2.10 on 2026-05-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name_completo",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="apelido",
            new_name="surname",
        ),
    ]
