# Generated by Django 5.2.10 on 2026-05-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="telefone",
            new_name="alternative_phone",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="data_nascimento",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="genero",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="nacionalidade",
            new_name="nationality",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="telefone_alternativo",
            new_name="phone",
        ),
    ]
