# Generated by Django 5.2.10 on 2026-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="editable",
            field=models.BooleanField(default=False),
        ),
    ]
