# Generated by Django 5.2.10 on 2026-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelextraaction",
            name="autorequest",
            field=models.BooleanField(default=False),
        ),
    ]
