# Generated by Django 5.2.10 on 2026-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_rename_telefone_person_alternative_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculine"), ("F", "Feminine"), ("O", "Others")],
                max_length=1,
                null=True,
            ),
        ),
    ]
