# Generated by Django 5.2.10 on 2026-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_alter_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelextraaction",
            name="action",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="app",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="label",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="managed_by",
            field=models.CharField(default="decorator", max_length=20),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="permission_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="position",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="tooltip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="modelextraaction",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="modelextraaction",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="modelextraaction",
            constraint=models.UniqueConstraint(
                fields=("app", "model", "action"), name="unique_model_extra_action"
            ),
        ),
    ]
