# Generated by Django 5.2.10 on 2026-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_rename_name_completo_person_full_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="perfil",
            new_name="profile",
        ),
        migrations.AlterField(
            model_name="file",
            name="funcionalidade",
            field=models.CharField(
                choices=[
                    ("File", "File"),
                    ("Profile", "Profile"),
                    ("Logo", "Logo"),
                    ("Photo", "Photo"),
                    ("Cover", "Cover"),
                ],
                default="File",
                max_length=100,
                null=True,
            ),
        ),
    ]
