# Generated by Django 5.2.10 on 2026-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_resaas",
            "0002_alter_address_state_alter_animationsetting_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="animationsetting",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="branchgroup",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="branchuser",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="branchusergroup",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="corsallowedorigin",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entityapp",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitygroup",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitymodel",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitytypeapp",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitytypegroup",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entitytypemodel",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="entityuser",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="layoutsetting",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="modelextra",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="typography",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
    ]
