# Generated by Django 5.2.10 on 2026-08-27 19:47

import django_resaas.models.entity
import django_resaas.models.entity_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_resaas",
            "0003_alter_address_state_alter_animationsetting_state_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="login_background_color",
            field=models.CharField(
                blank=True, default="#ffffff", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="login_background_gradient",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="login_background_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=django_resaas.models.entity.login_background_path,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="login_background_overlay",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entity",
            name="login_background_type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                ],
                default="color",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="login_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("center", "Center"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="center",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_background_color",
            field=models.CharField(
                blank=True, default="#ffffff", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_background_gradient",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_background_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=django_resaas.models.entity_type.login_background_path,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_background_overlay",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_background_type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                ],
                default="color",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="login_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("center", "Center"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="center",
                max_length=30,
            ),
        ),
    ]
