# Generated by Django 5.2.10 on 2026-08-27 20:02

import django.core.validators
import django_resaas.models.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0004_entity_login_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="login_background_color",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_gradient",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=django_resaas.models.entity.login_background_path,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("center", "Center"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=50),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_overlay",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
