# Generated by Django 5.2.10 on 2026-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0005_alter_entity_login_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="display_logo_login",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
