# Generated by Django 5.2.10 on 2026-08-27 20:19

import django.core.validators
import django.db.models.deletion
import django_resaas.models.entity
import django_resaas.models.entity_type
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0006_entity_display_logo_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="admins",
            field=models.ManyToManyField(
                help_text="Users with administrative access to this entity.",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="animation_settings",
            field=models.ForeignKey(
                blank=True,
                help_text="Animation configuration used by this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.animationsetting",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="disc_free_space",
            field=models.FloatField(
                default=1048576.0,
                help_text="Remaining disk space available to this entity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="disc_space",
            field=models.FloatField(
                default=1048576.0,
                help_text="Maximum disk space allocated to this entity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="disc_used_space",
            field=models.FloatField(
                default=0.0,
                help_text="Disk space currently used by this entity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="display_bar",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Display the application bar for this entity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="display_logo",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Display the entity logo in the application.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="display_logo_login",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Display the entity logo on the login page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="display_qr",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Display the QR code when available.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.ForeignKey(
                help_text="Entity type associated with this entity.",
                on_delete=django.db.models.deletion.CASCADE,
                to="django_resaas.entitytype",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="layout_settings",
            field=models.ForeignKey(
                blank=True,
                help_text="Layout configuration used by this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.layoutsetting",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Background color for the login page, for example #ffffff. Used when the background type is Color.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_gradient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="CSS gradient used as the login background, for example linear-gradient(135deg, #1976d2, #26a69a).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Background image displayed on the login page. Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.models.entity.login_background_path,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Dark overlay opacity applied to the login background. Use a value between 0 and 1. Leave empty to inherit from the entity type.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                ],
                default=None,
                help_text="Type of background used on the login page. Leave empty to inherit from the entity type.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="login_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("center", "Center"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default=None,
                help_text="Position of the login form. Leave empty to inherit from the entity type.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="logo",
            field=models.FileField(
                blank=True,
                default="logo.png",
                help_text="Logo displayed for this entity.",
                upload_to=django_resaas.models.entity.logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(
                default="-", help_text="Name of the entity.", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="rodape",
            field=models.CharField(
                help_text="Footer text displayed for this entity.",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="site",
            field=models.CharField(
                default="-",
                help_text="Website or domain associated with the entity.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Visual theme used by this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.theme",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="typography",
            field=models.ForeignKey(
                blank=True,
                help_text="Typography configuration used by this entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.typography",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="animation_settings",
            field=models.ForeignKey(
                blank=True,
                help_text="Default animation configuration used by this entity type.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.animationsetting",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="crair_entity",
            field=models.BooleanField(
                default=True,
                help_text="Allow entities to be created for this entity type.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="icon",
            field=models.FileField(
                blank=True,
                default="logo.png",
                help_text="Default icon used by this entity type.",
                upload_to=django_resaas.models.entity_type.icon_path,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="label",
            field=models.CharField(
                help_text="Display label used to identify this entity type.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="layout_settings",
            field=models.ForeignKey(
                blank=True,
                help_text="Default layout configuration used by this entity type.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.layoutsetting",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="license",
            field=models.TextField(
                default="license",
                help_text="License information associated with this entity type.",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Default login background color, for example #ffffff. Used when the background type is Color.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_gradient",
            field=models.CharField(
                blank=True,
                help_text="Default CSS gradient used on the login page, for example linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_image",
            field=models.FileField(
                blank=True,
                help_text="Default background image displayed on the login page. Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.models.entity_type.login_background_path,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_overlay",
            field=models.FloatField(
                default=0.0,
                help_text="Default dark overlay opacity applied to the login background. Use a value between 0 and 1.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_background_type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                ],
                default="color",
                help_text="Default background type used on the login page. Entities may override this setting.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="login_position",
            field=models.CharField(
                choices=[
                    ("top-left", "Top Left"),
                    ("top-right", "Top Right"),
                    ("center", "Center"),
                    ("bottom-left", "Bottom Left"),
                    ("bottom-right", "Bottom Right"),
                ],
                default="center",
                help_text="Default position of the login form. Entities may override this setting.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="name",
            field=models.CharField(
                help_text="Name of the entity type.", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="ordem",
            field=models.IntegerField(
                default=2, help_text="Display order of this entity type."
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Default visual theme used by this entity type.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.theme",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="typography",
            field=models.ForeignKey(
                blank=True,
                help_text="Default typography configuration used by this entity type.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_resaas.typography",
            ),
        ),
    ]
