# Generated by Django 5.2.10 on 2026-08-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_resaas",
            "0007_alter_entity_admins_alter_entity_animation_settings_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="display_logo_login",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Display the entity type logo on the login page.",
                null=True,
            ),
        ),
    ]
