# Generated by Django 5.2.10 on 2026-09-04 10:19

import django.db.models.deletion
import django_resaas.engine.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("person", "branch")},
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="ISO 4217 currency code (e.g. MZN, USD, EUR).",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="probation_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("terminated", "Terminated"),
                ],
                default="draft",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("probation", "Probation"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                    ("resigned", "Resigned"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contractor", "Contractor"),
                    ("intern", "Intern"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("entity", "contract_number")},
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("entity", "code"), ("person", "branch")},
        ),
        migrations.CreateModel(
            name="JobGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower first — used to order grades (e.g. Junior=1, Senior=2).",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_branch",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entity",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
                "unique_together": {("entity", "name")},
            },
            bases=(
                django_resaas.engine.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.jobgrade",
            ),
        ),
    ]
