# Generated by Django 5.2.10 on 2026-09-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryaction",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinarycase",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeegoal",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeoffboarding",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeoffboardingtask",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeonboarding",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeonboardingtask",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalarycomponent",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeshift",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeespecialty",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeetraining",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="jobgrade",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="jobposition",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalanceentry",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingtemplate",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingtemplatetask",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="performancecycle",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="resignation",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="reviewcompetencyrating",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="shiftschedule",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="termination",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
    ]
