# Generated by Django 5.2.10 on 2026-09-04 12:06

import django.db.models.deletion
import django_resaas.engine.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
        ("hr", "0002_alter_employee_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="early_departure_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("web", "Web"),
                    ("mobile", "Mobile"),
                    ("biometric", "Biometric"),
                    ("rfid", "RFID"),
                    ("api", "API"),
                    ("external_device", "External Device"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("date", models.DateField()),
                ("is_entity_wide", models.BooleanField(default=True)),
                ("is_recurring", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_branch",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entity",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("entity", "branch", "date", "name")},
            },
            bases=(
                django_resaas.engine.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
