# Generated by Django 5.2.10 on 2026-09-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_leavetype_leaverequest_leavebalanceentry_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leavetype",
            options={"ordering": ["name"]},
        ),
    ]
