# Generated by Django 5.2.10 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationoutbox",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="fallback_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
