# Generated by Django 5.2.10 on 2026-09-13 19:39

import django.db.models.deletion
import django_resaas.saas.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_alter_animationsetting_button_animation_and_more"),
        ("notifications", "0002_alter_notificationoutbox_channel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationProviderCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=8,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=50)),
                ("encrypted_config", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_provider_credentials",
                        to="django_resaas.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_provider_credentials",
                        to="django_resaas.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "branch", "channel"),
                        name="unique_notification_provider_credential_entity_branch_channel",
                    )
                ],
            },
            bases=(
                django_resaas.saas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
