# Generated by Django 5.2.10 on 2026-09-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationprovidercredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdeliveryattempt",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationoutbox",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationprovidercredential",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
    ]
