# Generated by Django 5.2.10 on 2026-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="father_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
