# Generated by Django 5.2.10 on 2026-09-05 22:20

import django_resaas.saas.models.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=django_resaas.saas.models.person.person_photo_path,
            ),
        ),
    ]
