# Generated by Django 5.2.10 on 2026-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="dashboard",
            field=models.CharField(
                choices=[("None", "None"), ("Auto", "Auto"), ("Manual", "Manual")],
                default="None",
                help_text="Define how the dashboard is generated for this entity type.",
            ),
        ),
    ]
