# Generated by Django 5.2.10 on 2026-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animationsetting",
            name="button_animation",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("ripple", "Ripple"),
                    ("pulse", "Pulse"),
                    ("bounce", "Bounce"),
                    ("scale", "Scale"),
                ],
                default="ripple",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animationsetting",
            name="card_animation",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("fade", "Fade"),
                    ("slide-up", "Slide Up"),
                    ("zoom", "Zoom"),
                ],
                default="fade",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animationsetting",
            name="hover_style",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("lift", "Lift"),
                    ("shadow", "Shadow"),
                    ("grow", "Grow"),
                    ("glow", "Glow"),
                ],
                default="lift",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animationsetting",
            name="modal_animation",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("scale", "Scale"),
                    ("fade", "Fade"),
                    ("slide-up", "Slide Up"),
                ],
                default="scale",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animationsetting",
            name="page_transition",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("fade", "Fade"),
                    ("slide-left", "Slide Left"),
                    ("slide-right", "Slide Right"),
                    ("slide-up", "Slide Up"),
                    ("slide-down", "Slide Down"),
                    ("scale", "Scale"),
                    ("zoom", "Zoom"),
                ],
                default="fade",
                max_length=20,
            ),
        ),
    ]
