# Generated by Django 5.2.10 on 2026-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_entitytype_dashboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="address",
        ),
        migrations.RemoveField(
            model_name="entitytype",
            name="dashboard",
        ),
        migrations.AddField(
            model_name="entity",
            name="dashboard",
            field=models.CharField(
                choices=[("None", "None"), ("Auto", "Auto"), ("Manual", "Manual")],
                default="Auto",
                help_text="Define how the dashboard is generated for this entity type.",
            ),
        ),
    ]
