# Generated by Django 5.2.10 on 2026-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_person_father_name_person_mother_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
