# Generated by Django 5.2.10 on 2026-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_resaas",
            "0003_remove_entity_address_remove_entitytype_dashboard_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layoutsetting",
            name="sidebar_position",
        ),
        migrations.AlterField(
            model_name="layoutsetting",
            name="sidebar_width",
            field=models.PositiveIntegerField(default=300),
        ),
    ]
