# Generated by Django 5.2.10 on 2026-09-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0004_remove_layoutsetting_sidebar_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="country_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="occupation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="layoutsetting",
            name="sidebar_mini_width",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="layoutsetting",
            name="sidebar_width",
            field=models.PositiveIntegerField(default=320),
        ),
        migrations.AlterField(
            model_name="person",
            name="alternative_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(
                blank=True, editable=False, max_length=300, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculine"), ("F", "Feminine"), ("O", "Others")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["surname"], name="django_resa_surname_6b9acc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["phone"], name="django_resa_phone_caf8d0_idx"),
        ),
    ]
