# Generated by Django 5.2.10 on 2026-09-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0004_person_address_generic_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="django_resaas.branch",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="django_resaas.entity",
            ),
        ),
    ]
