# Generated by Django 5.2.10 on 2026-09-17 23:19

import django.db.models.deletion
import django_resaas.saas.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_resaas",
            "0005_person_country_of_birth_person_marital_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "alternative_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="django_resaas.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Contact",
                "verbose_name_plural": "Person Contacts",
                "ordering": ["-is_primary", "-is_emergency", "name"],
                "indexes": [
                    models.Index(
                        fields=["person", "is_primary"],
                        name="django_resa_person__ac25ef_idx",
                    ),
                    models.Index(
                        fields=["person", "is_emergency"],
                        name="django_resa_person__2305c7_idx",
                    ),
                ],
            },
            bases=(
                django_resaas.saas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
