# Generated by Django 5.2.10 on 2026-09-14 10:16

import django_resaas.saas.models.branch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0005_file_branch_file_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Shown on the map card and branch listings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Shown on the map card and branch listings.",
                null=True,
                upload_to=django_resaas.saas.models.branch.branch_photo_path,
            ),
        ),
    ]
