# Generated by Django 5.2.10 on 2026-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0006_personcontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="person",
            name="timezone",
        ),
        migrations.AddField(
            model_name="person",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculine"), ("F", "Feminine"), ("O", "Others")],
                max_length=100,
                null=True,
            ),
        ),
    ]
