# Generated by Django 5.2.10 on 2026-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0007_remove_person_middle_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                null=True,
            ),
        ),
    ]
