# Generated by Django 5.2.10 on 2026-09-09 21:29

import django.core.validators
import django.db.models.deletion
import django_resaas.engine.core.base.mixins.model.label_value
import django_resaas.engine.models.mixins.visual_area
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0002_person_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="footer_background_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Used when the background type is Color.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="footer_background_gradient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="footer_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="footer_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="footer_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                    ("transparent", "Transparent"),
                ],
                default=None,
                help_text="Background type for the footer. Null = inherit.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="footer_text_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Text color used over the footer.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_background_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Used when the background type is Color.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_background_gradient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                    ("transparent", "Transparent"),
                ],
                default=None,
                help_text="Background type for the header. Null = inherit.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="header_text_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Text color used over the header.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_background_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Used when the background type is Color.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_background_gradient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                    ("transparent", "Transparent"),
                ],
                default=None,
                help_text="Background type for the footer. Null = inherit.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="footer_text_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Text color used over the footer.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_background_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Used when the background type is Color.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_background_gradient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_background_image",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Used when the background type is Image.",
                null=True,
                upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_background_overlay",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_background_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("color", "Color"),
                    ("gradient", "Gradient"),
                    ("image", "Image"),
                    ("transparent", "Transparent"),
                ],
                default=None,
                help_text="Background type for the header. Null = inherit.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entitytype",
            name="header_text_color",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Text color used over the header.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserThemeOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=8,
                    ),
                ),
                (
                    "header_background_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("color", "Color"),
                            ("gradient", "Gradient"),
                            ("image", "Image"),
                            ("transparent", "Transparent"),
                        ],
                        default=None,
                        help_text="Background type for the header. Null = inherit.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "header_background_color",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Used when the background type is Color.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "header_background_gradient",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "header_background_image",
                    models.FileField(
                        blank=True,
                        default=None,
                        help_text="Used when the background type is Image.",
                        null=True,
                        upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
                    ),
                ),
                (
                    "header_background_overlay",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "header_text_color",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Text color used over the header.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "footer_background_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("color", "Color"),
                            ("gradient", "Gradient"),
                            ("image", "Image"),
                            ("transparent", "Transparent"),
                        ],
                        default=None,
                        help_text="Background type for the footer. Null = inherit.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "footer_background_color",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Used when the background type is Color.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "footer_background_gradient",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="CSS gradient, e.g. linear-gradient(135deg, #1976d2, #26a69a). Used when the background type is Gradient.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "footer_background_image",
                    models.FileField(
                        blank=True,
                        default=None,
                        help_text="Used when the background type is Image.",
                        null=True,
                        upload_to=django_resaas.engine.models.mixins.visual_area.visual_area_upload_path,
                    ),
                ),
                (
                    "footer_background_overlay",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Dark overlay opacity (0-1), applied over image/gradient.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "footer_text_color",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Text color used over the footer.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_override",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Theme Override",
                "verbose_name_plural": "User Theme Overrides",
            },
            bases=(
                django_resaas.engine.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
