# Generated by Django 5.2.10 on 2026-05-18 16:10

import django.db.models.deletion
import django_resaas.core.base.mixins.model.label_value
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_resaas", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["title"],
                "permissions": (),
            },
            bases=(
                django_resaas.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="employee",
            name="unique_person_branch",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="codigo",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="data_admissao",
            new_name="hire_date",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="gestor",
            new_name="manager",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="cargo",
            new_name="position",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="data_saida",
            new_name="termination_date",
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("person", "branch")},
        ),
        migrations.AddField(
            model_name="specialty",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_branch",
                to="django_resaas.branch",
            ),
        ),
        migrations.AddField(
            model_name="specialty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specialty",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entity",
                to="django_resaas.entity",
            ),
        ),
        migrations.AddField(
            model_name="specialty",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="employee",
            name="ativo",
        ),
        migrations.AlterUniqueTogether(
            name="specialty",
            unique_together={("entity", "title")},
        ),
    ]
