# Generated by Django 5.2.10 on 2026-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_attendance_state_alter_department_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeeshift",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="employeespecialty",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="jobposition",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="shiftschedule",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="state",
            field=models.CharField(
                choices=[("Inactive", "Inactive"), ("Active", "Active")],
                default="Inactive",
            ),
        ),
    ]
