
# hr/serializers/employee.py

from rest_framework import serializers
from django_resaas.engine.core.base.serializers import BaseSerializer

from django_resaas.hr.models.employee import Employee
from django_resaas.hr.models.job_position import JobPosition
from django_resaas.hr.models.job_grade import JobGrade

from django_resaas.engine.models.person import Person

from django_resaas.engine.data.person.serializers.person import PersonSerializer
from django_resaas.hr.serializers.job_position import JobPositionSerializer
from django_resaas.hr.serializers.job_grade import JobGradeSerializer


class EmployeeSerializer(BaseSerializer):

    # Explicitly optional: model field has blank=True (auto-generated by
    # EmployeeAPIView.perform_create via EmployeeNumberService when
    # omitted), but DRF's implicit UniqueTogetherValidator for
    # ('entity', 'code') would otherwise force it required=True since
    # the field has no model-level default.
    code = serializers.CharField(required=False, allow_blank=True)

    person = serializers.PrimaryKeyRelatedField(
        queryset=Person.objects.all(),
        write_only=True
    )

    person_data = PersonSerializer(
        source='person',
        read_only=True
    )

    position = serializers.PrimaryKeyRelatedField(
        queryset=JobPosition.objects.all(),
        write_only=True,
        required=False,
        allow_null=True
    )

    position_data = JobPositionSerializer(
        source='position',
        read_only=True
    )

    manager = serializers.PrimaryKeyRelatedField(
        queryset=Employee.objects.all(),
        write_only=True,
        required=False,
        allow_null=True
    )

    manager_data = serializers.SerializerMethodField()

    job_grade = serializers.PrimaryKeyRelatedField(
        queryset=JobGrade.objects.all(),
        write_only=True,
        required=False,
        allow_null=True
    )

    job_grade_data = JobGradeSerializer(
        source='job_grade',
        read_only=True
    )

    class Meta:
        model = Employee
        fields = "__all__"

    def get_manager_data(self, obj):
        if not obj.manager:
            return None

        return {
            "id": obj.manager.id,
            "label": str(obj.manager)
        }

    def validate(self, attrs):
        attrs = super().validate(attrs)

        # PrimaryKeyRelatedField querysets above are deliberately
        # unscoped (Person/JobPosition/Employee/JobGrade.objects.all())
        # so validation errors are attributed to the right field instead
        # of the object just vanishing from a tenant-filtered queryset -
        # the actual tenant boundary is enforced here, not by hiding
        # other Entities' rows from the field's choices.
        request = self.context.get("request")
        entity_id = getattr(request, "entity_id", None) if request else None

        if entity_id:
            for field_name in ("position", "job_grade", "manager"):
                related = attrs.get(field_name)

                if related is not None and str(related.entity_id) != str(entity_id):
                    raise serializers.ValidationError({
                        field_name: "Does not belong to the current entity."
                    })

        return attrs