# Generated by Django 5.2.10 on 2026-09-05 09:07

import django_resaas.engine.core.base.mixins.model.label_value
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("sku", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                django_resaas.engine.core.base.mixins.model.label_value.LabelValueMixin,
                models.Model,
            ),
        ),
    ]
