
MENU = "Hr"
ICON = "menu"
SUBMENUS = [
    {
        "menu": "Dashboard",
        "icon": "dashboard",
        "role": "view_hr_dashboard",
        "route": "view_hr_dashboard",
    },
    {
        "menu": "Employee",
        "icon": "person",  # 🔥 segurança
        "role": "list_employee",
        "route": "list_employee",
        "add_role": "add_employee",
        "add_route": "add_employee",
        "crud": {"module": "hr", "model": "Employee"},
    },
    {
        "menu": "Department",
        "icon": "corporate_fare",
        "role": "list_department",
        "route": "list_department",
        "add_role": "add_department",
        "add_route": "add_department",
        "crud": {"module": "hr", "model": "Department"},
    },
    {
        "menu": "Job Position",
        "icon": "badge",
        "role": "list_jobposition",
        "route": "list_jobposition",
        "add_role": "add_jobposition",
        "add_route": "add_jobposition",
        "crud": {"module": "hr", "model": "JobPosition"},
    },
    {
        "menu": "Contract",
        "icon": "assignment",
        "role": "list_contract",
        "route": "list_contract",
        "add_role": "add_contract",
        "add_route": "add_contract",
        "crud": {"module": "hr", "model": "Contract"},
    },
    {
        "menu": "Specialty",
        "icon": "star",
        "role": "list_specialty",
        "route": "list_specialty",
        "add_role": "add_specialty",
        "add_route": "add_specialty",
        "crud": {"module": "hr", "model": "Specialty"},
    },
    {
        "menu": "Employee Specialty",
        "icon": "workspace_premium",
        "role": "list_employeespecialty",
        "route": "list_employeespecialty",
        "add_role": "add_employeespecialty",
        "add_route": "add_employeespecialty",
        "crud": {"module": "hr", "model": "EmployeeSpecialty"},
    },
    {
        "menu": "Shift",
        "icon": "schedule",
        "role": "list_shift",
        "route": "list_shift",
        "add_role": "add_shift",
        "add_route": "add_shift",
        "crud": {"module": "hr", "model": "Shift"},
    },
    {
        "menu": "Employee Shift",
        "icon": "event_available",
        "role": "list_employeeshift",
        "route": "list_employeeshift",
        "add_role": "add_employeeshift",
        "add_route": "add_employeeshift",
        "crud": {"module": "hr", "model": "EmployeeShift"},
    },
    {
        "menu": "Shift Schedule",
        "icon": "calendar_month",
        "role": "list_shiftschedule",
        "route": "list_shiftschedule",
        "add_role": "add_shiftschedule",
        "add_route": "add_shiftschedule",
        "crud": {"module": "hr", "model": "ShiftSchedule"},
    },
    {
        "menu": "Attendance",
        "icon": "how_to_reg",
        "role": "list_attendance",
        "route": "list_attendance",
        "add_role": "add_attendance",
        "add_route": "add_attendance",
        "crud": {"module": "hr", "model": "Attendance"},
    },
    {
        "menu": "Salary Component",
        "icon": "payments",
        "role": "list_salarycomponent",
        "route": "list_salarycomponent",
        "add_role": "add_salarycomponent",
        "add_route": "add_salarycomponent",
        "crud": {"module": "hr", "model": "SalaryComponent"},
    },
    {
        "menu": "Employee Salary",
        "icon": "attach_money",
        "role": "list_employeesalary",
        "route": "list_employeesalary",
        "add_role": "add_employeesalary",
        "add_route": "add_employeesalary",
        "crud": {"module": "hr", "model": "EmployeeSalary"},
    },
    {
        "menu": "Payroll Period",
        "icon": "date_range",
        "role": "list_payrollperiod",
        "route": "list_payrollperiod",
        "add_role": "add_payrollperiod",
        "add_route": "add_payrollperiod",
        "crud": {"module": "hr", "model": "PayrollPeriod"},
    },
    {
        "menu": "Payroll",
        "icon": "receipt_long",
        "role": "list_payroll",
        "route": "list_payroll",
        "add_role": "add_payroll",
        "add_route": "add_payroll",
        "crud": {"module": "hr", "model": "Payroll"},
    },
    {
        "menu": "Payroll Item",
        "icon": "list_alt",
        "role": "list_payrollitem",
        "route": "list_payrollitem",
        "add_role": "add_payrollitem",
        "add_route": "add_payrollitem",
        "crud": {"module": "hr", "model": "PayrollItem"},
    },
    {
        "menu": "Payslip",
        "icon": "receipt",
        "role": "list_payslip",
        "route": "list_payslip",
        "add_role": "add_payslip",
        "add_route": "add_payslip",
        "crud": {"module": "hr", "model": "Payslip"},
    },
]
